# permissions for end users to view accesstokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: accesstoken-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gcp-temp-secret
    app.kubernetes.io/part-of: gcp-temp-secret
    app.kubernetes.io/managed-by: kustomize
  name: accesstoken-viewer-role
rules:
- apiGroups:
  - gcpsecret.secret.arpan.io
  resources:
  - accesstokens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gcpsecret.secret.arpan.io
  resources:
  - accesstokens/status
  verbs:
  - get
